Write-Host ""
Write-Host "Please COPY and PASTE the following files and folders from your Framework 4 template into this folder:"
Write-Host "(The updater deleted them, so you should NOT get overwrite prompts)"
Write-Host " - Description.ext"
Write-Host " - Init.sqf"
Write-Host " - version.hpp"
Write-Host " - CurrentAddonOptionsImportSettings.txt"
Write-Host " - Gear  (folder at mission root)"
Write-Host ""
Write-Host "NOTE: Do NOT paste CustomGear\ — your mission-specific loadouts there are preserved."
Write-Host "NOTE: If you have custom kits, best save them separately and restore after, or use GitHub Desktop to undo selectively."
Write-Host ""
Write-Host "Press ENTER when done."
[void][System.Console]::ReadLine()
