
	#include "Common\Module.hpp"
	#include "Gear\Module.hpp"
//	#include "HeadlessController\Module.hpp"
	#include "MHQ\Module.hpp"
	#include "MiscSettings\Module.hpp"
	#include "Radios\Module.hpp"
	#include "SetDifficulty\Module.hpp"
	#include "Settings_ACE\Module.hpp"
	#include "StartUp\Module.hpp"

//	Extra Modules
//	#include "Effects\Module.hpp"
//	#include "Example\Module.hpp"
//	#include "HeadlessController_Legacy\Module.hpp"
//	#include "Loadout\Module.hpp"
//	#include "Respawn\Module.hpp"
//	#include "SetDifficulty_Legacy\Module.hpp"
//	#include "VCOMAI\Module.hpp"
//	#include "AAC_Setup\Module.hpp"
