Write-Host ""
Write-Host "Copy and paste the following from the Framework 4 template folder into this mission folder:"
Write-Host "(These were deleted — no overwrite prompts)"
Write-Host ""
Write-Host "  Gear\                              (folder)"
Write-Host "  CurrentAddonOptionsImportSettings.txt"
Write-Host "  Description.ext"
Write-Host "  Init.sqf"
Write-Host "  version.hpp"
Write-Host ""
Write-Host "Leave these alone — they are yours:"
Write-Host "  CustomGear\     (your loadouts — already preserved)"
Write-Host "  spawnList.sqf   (your spawn config — not touched)"
Write-Host "  mission.sqm     (already updated by this script)"
Write-Host ""
Write-Host "Press ENTER when done copying."
[void][System.Console]::ReadLine()
