#include "script_Component.hpp"

PREP(actions);
PREP(getAttachments);
PREP(getLoadoutClass);
PREP(Handler);
PREP(Init);
PREP(replaceAttachments);

GVAR(Enabled_101) = true;
GVAR(Enabled_201) = true;
GVAR(Enabled_301) = true;
GVAR(Enabled_302) = true;

GVAR(Index101) = 0;
GVAR(Index201) = 0;
GVAR(Index301) = 0;
GVAR(Index302) = 0;
GVAR(Stamina) = true;
GVAR(StaminaCoef) = 0.5;

[
	QGVAR(Blufor), "LIST",
	["Loadout Blufor", "Loadout for Blufor units"],
	QUOTE(ADDON),
	[
		[
			"AAF-SF-W",
			"AAF-W",
			"AFGHAN-W",
			"AFRICAN-ARMY",
			"AUS-TAN",
			"BAF-D",
			"BAF-W",
			"BAF-W-FALK",
			"CBRN-WINTER",
			"CDF-W",
			"CHDKZ-SF-W",
			"CHINA",
			"CSAT-H",
			"CSAT-SF-W",
			"CSAT-U",
			"CSAT-W",
			"CTRG-D",
			"CTRG-W",
			"CUSTOM-E",
			"CUSTOM-I",
			"CUSTOM-W",
			"CZECH-D",
			"CZECH-SOVIET-W",
			"CZECH-W",
			"FINLAND-W",
			"FRANCE-D",
			"FRANCE-W",
			"GERMAN-D",
			"GERMAN-W",
			"INSURGENT-AFRICA",
			"INSURGENT-CHDKZ",
			"INSURGENT-FIA",
			"INSURGENT-MALDEN",
			"INSURGENT-ME",
			"INSURGENT-TANOA",
			"IRAQ-SF",
			"IRISH-UN",
			"ISLAMICSTATE",
			"ISRAELI",
			"LIVONIA-W",
			"MALDEN-W",
			"NATO-D",
			"NATO-W",
			"PMC",
			"RUSSIAN-SF-W",
			"RUSSIAN-W",
			"RWANDA-W",
			"SOVIET-D",
			"SOVIET-SF-D",
			"SOVIET-W",
			"SWEDISH",
			"SYRIA-W",
			"TAKISTAN-D",
			"TAKISTAN-SF-D",
			"TANOA-ARMY",
			"TANOA-SF",
			"TURKEY-D",
			"UKRAINE-W",
			"USA-CW-W",
			"USA-D",
			"USA-W",
			"USMC-D",
			"USMC-W"
		],
		[
			"AAF SF Woodland",
			"AAF Woodland",
			"Afghan National Army Woodland",
			"African Army Desert",
			"Austrian Tan",
			"British Armed Forces Desert",
			"British Armed Forces Woodland",
			"British Falklands Woodland",
			"CBRN Winter",
			"Chernarussian Defence Force",
			"ChDkz SF Woodland",
			"Chinese Armed Forces",
			"CSAT Hex",
			"CSAT SF Woodland",
			"CSAT Urban",
			"CSAT Woodland",
			"CTRG Desert",
			"CTRG Woodland",
			"CUSTOM-East",
			"CUSTOM-Independent",
			"CUSTOM-West",
			"Czech Desert",
			"Czech Soviet Woodland",
			"Czech Woodland",
			"Finnish Army Woodland",
			"French Army Desert",
			"French Army Woodland",
			"Bundeswehr Tropentarn",
			"Bundeswehr Flecktarn",
			"INSURGENT African",
			"INSURGENT ChDkz",
			"INSURGENT FIA",
			"INSURGENT Malden",
			"INSURGENT Middle Eastern",
			"INSURGENT Tanoan",
			"Iraqi Special Forces",
			"Irish United Nations",
			"Islamic State",
			"Israeli Defence Force",
			"Livonia Woodland",
			"Malden Defence Force Woodland",
			"NATO Desert",
			"NATO Woodland",
			"PMC",
			"Russian SF Woodland",
			"Russian Woodland",
			"Rwanda Defence Force Woodland",
			"Soviet Desert",
			"Soviet SF Desert",
			"Soviet Woodland",
			"Swedish Army",
			"Syrian Army Woodland",
			"Takistani Desert",
			"Takistani SF Desert",
			"Tanoan Army",
			"Tanoan Special Forces",
			"Turkish Army Desert",
			"Ukrainian Army",
			"US Army Cold War Woodland",
			"US Army 2000 UCP",
			"US Army 2010 MTP",
			"USMC Marpat Desert",
			"USMC Marpat Woodland"
		],
		0
	], CBA_SERVEROVERWRITE
] call FUNCMAIN(settingsInit);

[
	QGVAR(Opfor),
	"LIST", ["Loadout Opfor", "Loadout for Opfor units"],
	QUOTE(ADDON),
	[
		[
			"AAF-SF-W",
			"AAF-W",
			"AFGHAN-W",
			"AFRICAN-ARMY",
			"AUS-TAN",
			"BAF-D",
			"BAF-W",
			"BAF-W-FALK",
			"CBRN-WINTER",
			"CDF-W",
			"CHDKZ-SF-W",
			"CHINA",
			"CSAT-H",
			"CSAT-SF-W",
			"CSAT-U",
			"CSAT-W",
			"CTRG-D",
			"CTRG-W",
			"CUSTOM-E",
			"CUSTOM-I",
			"CUSTOM-W",
			"CZECH-D",
			"CZECH-SOVIET-W",
			"CZECH-W",
			"FINLAND-W",
			"FRANCE-D",
			"FRANCE-W",
			"GERMAN-D",
			"GERMAN-W",
			"INSURGENT-AFRICA",
			"INSURGENT-CHDKZ",
			"INSURGENT-FIA",
			"INSURGENT-MALDEN",
			"INSURGENT-ME",
			"INSURGENT-TANOA",
			"IRAQ-SF",
			"IRISH-UN",
			"ISLAMICSTATE",
			"ISRAELI",
			"LIVONIA-W",
			"MALDEN-W",
			"NATO-D",
			"NATO-W",
			"PMC",
			"RUSSIAN-SF-W",
			"RUSSIAN-W",
			"RWANDA-W",
			"SOVIET-D",
			"SOVIET-SF-D",
			"SOVIET-W",
			"SWEDISH",
			"SYRIA-W",
			"TAKISTAN-D",
			"TAKISTAN-SF-D",
			"TANOA-ARMY",
			"TANOA-SF",
			"TURKEY-D",
			"UKRAINE-W",
			"USA-CW-W",
			"USA-D",
			"USA-W",
			"USMC-D",
			"USMC-W"
		],
		[
			"AAF SF Woodland",
			"AAF Woodland",
			"Afghan National Army Woodland",
			"African Army Desert",
			"Austrian Tan",
			"British Armed Forces Desert",
			"British Armed Forces Woodland",
			"British Falklands Woodland",
			"CBRN Winter",
			"Chernarussian Defence Force",
			"ChDkz SF Woodland",
			"Chinese Armed Forces",
			"CSAT Hex",
			"CSAT SF Woodland",
			"CSAT Urban",
			"CSAT Woodland",
			"CTRG Desert",
			"CTRG Woodland",
			"CUSTOM-East",
			"CUSTOM-Independent",
			"CUSTOM-West",
			"Czech Desert",
			"Czech Soviet Woodland",
			"Czech Woodland",
			"Finnish Army Woodland",
			"French Army Desert",
			"French Army Woodland",
			"Bundeswehr Tropentarn",
			"Bundeswehr Flecktarn",
			"INSURGENT African",
			"INSURGENT ChDkz",
			"INSURGENT FIA",
			"INSURGENT Malden",
			"INSURGENT Middle Eastern",
			"INSURGENT Tanoan",
			"Iraqi Special Forces",
			"Irish United Nations",
			"Islamic State",
			"Israeli Defence Force",
			"Livonia Woodland",
			"Malden Defence Force Woodland",
			"NATO Desert",
			"NATO Woodland",
			"PMC",
			"Russian SF Woodland",
			"Russian Woodland",
			"Rwanda Defence Force Woodland",
			"Soviet Desert",
			"Soviet SF Desert",
			"Soviet Woodland",
			"Swedish Army",
			"Syrian Army Woodland",
			"Takistani Desert",
			"Takistani SF Desert",
			"Tanoan Army",
			"Tanoan Special Forces",
			"Turkish Army Desert",
			"Ukrainian Army",
			"US Army Cold War Woodland",
			"US Army 2000 UCP",
			"US Army 2010 MTP",
			"USMC Marpat Desert",
			"USMC Marpat Woodland"
		],
		0
	]
	, CBA_SERVEROVERWRITE
] call FUNCMAIN(settingsInit);

[
	QGVAR(Independent),
	"LIST", ["Loadout Independent", "Loadout for Independent units"],
	QUOTE(ADDON),
	[
		[
			"AAF-SF-W",
			"AAF-W",
			"AFGHAN-W",
			"AFRICAN-ARMY",
			"AUS-TAN",
			"BAF-D",
			"BAF-W",
			"BAF-W-FALK",
			"CBRN-WINTER",
			"CDF-W",
			"CHDKZ-SF-W",
			"CHINA",
			"CSAT-H",
			"CSAT-SF-W",
			"CSAT-U",
			"CSAT-W",
			"CTRG-D",
			"CTRG-W",
			"CUSTOM-E",
			"CUSTOM-I",
			"CUSTOM-W",
			"CZECH-D",
			"CZECH-SOVIET-W",
			"CZECH-W",
			"FINLAND-W",
			"FRANCE-D",
			"FRANCE-W",
			"GERMAN-D",
			"GERMAN-W",
			"INSURGENT-AFRICA",
			"INSURGENT-CHDKZ",
			"INSURGENT-FIA",
			"INSURGENT-MALDEN",
			"INSURGENT-ME",
			"INSURGENT-TANOA",
			"IRAQ-SF",
			"IRISH-UN",
			"ISLAMICSTATE",
			"ISRAELI",
			"LIVONIA-W",
			"MALDEN-W",
			"NATO-D",
			"NATO-W",
			"PMC",
			"RUSSIAN-SF-W",
			"RUSSIAN-W",
			"RWANDA-W",
			"SOVIET-D",
			"SOVIET-SF-D",
			"SOVIET-W",
			"SWEDISH",
			"SYRIA-W",
			"TAKISTAN-D",
			"TAKISTAN-SF-D",
			"TANOA-ARMY",
			"TANOA-SF",
			"TURKEY-D",
			"UKRAINE-W",
			"USA-CW-W",
			"USA-D",
			"USA-W",
			"USMC-D",
			"USMC-W"
		],
		[
			"AAF SF Woodland",
			"AAF Woodland",
			"Afghan National Army Woodland",
			"African Army Desert",
			"Austrian Tan",
			"British Armed Forces Desert",
			"British Armed Forces Woodland",
			"British Falklands Woodland",
			"CBRN Winter",
			"Chernarussian Defence Force",
			"ChDkz SF Woodland",
			"Chinese Armed Forces",
			"CSAT Hex",
			"CSAT SF Woodland",
			"CSAT Urban",
			"CSAT Woodland",
			"CTRG Desert",
			"CTRG Woodland",
			"CUSTOM-East",
			"CUSTOM-Independent",
			"CUSTOM-West",
			"Czech Desert",
			"Czech Soviet Woodland",
			"Czech Woodland",
			"Finnish Army Woodland",
			"French Army Desert",
			"French Army Woodland",
			"Bundeswehr Tropentarn",
			"Bundeswehr Flecktarn",
			"INSURGENT African",
			"INSURGENT ChDkz",
			"INSURGENT FIA",
			"INSURGENT Malden",
			"INSURGENT Middle Eastern",
			"INSURGENT Tanoan",
			"Iraqi Special Forces",
			"Irish United Nations",
			"Islamic State",
			"Israeli Defence Force",
			"Livonia Woodland",
			"Malden Defence Force Woodland",
			"NATO Desert",
			"NATO Woodland",
			"PMC",
			"Russian SF Woodland",
			"Russian Woodland",
			"Rwanda Defence Force Woodland",
			"Soviet Desert",
			"Soviet SF Desert",
			"Soviet Woodland",
			"Swedish Army",
			"Syrian Army Woodland",
			"Takistani Desert",
			"Takistani SF Desert",
			"Tanoan Army",
			"Tanoan Special Forces",
			"Turkish Army Desert",
			"Ukrainian Army",
			"US Army Cold War Woodland",
			"US Army 2000 UCP",
			"US Army 2010 MTP",
			"USMC Marpat Desert",
			"USMC Marpat Woodland"
		],
		0
	],CBA_SERVEROVERWRITE
] call FUNCMAIN(settingsInit);

[
	QGVAR(Civilian),
	"LIST", ["Loadout Civilian", "Loadout for Civilian units"],
	QUOTE(ADDON),
	[
		[
			"CIVI-ALTIS",
			"CIVI-CHERNARUS",
			"CIVI-TAKISTAN",
			"CIVI-AFRICA"
		],
		[
			"ALTIS",
			"CHERNARUS",
			"TAKISTAN",
			"AFRICAN"
		],
		0
	], CBA_SERVEROVERWRITE
] call FUNCMAIN(settingsInit);

[
	QGVAR(Auto_Assign), "LIST",
	["Auto assign gear", "automaticly gives gear to spawned units"],
	QUOTE(ADDON),
	[
		[0,1,2,3],
		["Disabled","All Units","Only Copied Units","Ignore Editor Placed"],
		1
	], CBA_SERVEROVERWRITE
] call FUNCMAIN(settingsInit);

[QGVAR(randomGear), "CHECKBOX", ["Random Role", "Should units get random gear"], QUOTE(ADDON), true, CBA_SERVEROVERWRITE] call FUNCMAIN(settingsInit);
[QGVAR(extraGear), "CHECKBOX", ["Gives units extra loadout", "Medics gets more supplies, AT gets more rockets etc"], QUOTE(ADDON), false, CBA_SERVEROVERWRITE] call FUNCMAIN(settingsInit);
[QGVAR(autoRemoveCargo), "CHECKBOX", ["Removes cargo for vehicles", "Automaticly removes cargo"], QUOTE(ADDON), true, CBA_SERVEROVERWRITE] call FUNCMAIN(settingsInit);
