/* Gear Settings */
GOL_MAGNIFIED_OPTICS = 1;
GOL_ARSENAL_ALLOWED = 1;

/* Logistics Settings */
GOL_NEKY_SERVICESTATION = 1;
GOL_NEKY_RESUPPLY = 1;
GOL_NEKY_PARADROP = 1;
GOL_NEKY_PICKUP = 1;

/* AI Settings*/
GOL_NEKY_SHARE = 0;
GOL_OKS_AMBIENCE = 1;
GOL_OKS_HUNT = 0;

/* HuntBases */
GOL_NEKY_HUNT = 0;
GOL_NEKY_AIRDROP = 0;

/* Optional Settings */
GOL_AAC_SETUP = 0;
GOL_OKS_TASK = 0;
GOL_OKS_TANKER = 0;

/* GOL Dynamic Scripts */
GOL_OKS_DYNAMIC = 1;
